### ISSUE TITLE
Vertaisarvio

### ISSUE THREAD

**Issue by Aleksipa** [Nurou/pathfinder-vis#3]
- Projektin lataaminen ja käynnistäminen lokaalisti vaati hieman selvittelyä. Projektin lataamisen ja riippuvuuksien hakemisen jälkeen sain seuraavanlaisen virhe -viestin:

"Failed to compile.

./src/algorithms/index.ts
Cannot find file: 'index.tsx' does not match the corresponding name on disk: './src/algorithms/Bfs/BFS'."

Muuttamalla kansion BFS nimen BFS -> Bfs sain projektin käynnistymään.

- Ohjelman kansiorakenne on selkeä ja muuttujien nimet on valittu siten, että ne ovat hyvin kuvaavia. Koodi on hyvin kommentoitua ja helppolukuista. 

- Testikattavuusraportti jäi yarn coverage ajon jälkeen tyhjäksi. Vaikutti kuitenkin siltä, että testejä oli kirjoitettu suhteellisen kattavasti. Testaamista voisi vielä jatkokehittää, kuten varmasti tarkoitus onkin, ja esimerkiksi algoritmien osalta voisi testata laajemmin niiden toimivuutta ja sitä, että tekevätkö ne todella niitä asioita mitä niiden on tarkoitus tehdä. 

- Yleisesti ottaen ohjelma toimii hienosti ja vaikuttaisi olevan hyvin aikataulussa. Hyvää duunia!

**Comment by Nurou** [comment]
Kiitos palautteesta!
