### ISSUE TITLE
Koodikatselmointi

### ISSUE THREAD

**Issue by lassilaiho** [Nurou/pathfinder-vis#4]
Ladattu klo 15.43 25.8.2020

- Testaus
  - Ohjelma ei läpäise kaikkia testejä. Moduuli `components/Visualiser/util`, jota käytetään osassa testeistä, näyttää puuttuvan kokonaan.
  - Testikattavuusraportin mukaan testien kattavuus on 0 %.
- Moduulin `algorithms/Bfs` käyttö ei onnistu, jos sen kansiota `src/algorithms/BFS` ei uudelleennimeä muotoon `src/algorithms/Bfs`. Ongelma johtuu luultavasti siitä, että käyttämäni käyttöjärjestelmä (Linux) erottelee isot ja pienet kirjaimet tiedostopoluissa. MacOS ja Windows eivät tee niin. Tästä syystä kansioiden ja tiedostojen nimien tulisi aina olla täsmälleen samat kuin niitä käyttävien moduulien import-lauseissa, jotta ne toimisivat varmasti kaikilla käyttöjärjestelmillä. TypeScript-kääntäjän asetus `forceConsistentCasingInFileNames` helpottaa näiden huomaamista.
- Array-olion prototyypin muokkaaminen kannattaa tehdä moduulitasolla eikä PriorityQueue-luokan konstruktorissa. Koska muutokset ovat globaaleja, niitä ei tarvitse tehdä joka kerta, kun uusi PriorityQueue-olio luodaan. Voisi myös olla hyvä idea jättää prototyyppi muokkaamatta ja tehdä sen sijaan uusi luokka, joka toteuttaa tarvittavat lisätoiminnallisuudet.
- Löysin muutaman bugin käyttöliittymästä:
  - Jos Show Distances -asetus on päällä, Reset Pathfinder -painikkeen painaminen piilottaa etäisyydet ruudukosta, mutta Show Distances -painike näyttää edelleen olevan painettuna. Jos haluaa saadaa ruudukon etäisyydet uudestaan näkyviin, on painiketta painettava uudestaan, jolloin se näyttää olevan pois päältä, vaikka se on oikeasti päällä.
  - Käyttöliittymässä on mahdollista painaa Regenerate Maze ja Reset Pathfinder -painikkeita kesken simulaation, jolloin käyttäjälle näkyvä ruudukko ei enää vastaa algoritmin prosessoimaa ruudukkoa, ja se esimerkiksi saattaa kulkea käyttäjälle näkyvien seinien läpi. Näiden painikkeiden painaminen voisi automaattisesti keskeyttää algoritmin suorituksen.
  - Käyttöliittymä mahdollistaa usean algoritmin päällekkäisen suorittamisen.

**Comment by Nurou** [comment]
Kiitos palautteesta :)
